apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Namespace
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-options: Prune=confirm,Delete=confirm
  - target:
      group: storage.k8s.io
      kind: StorageClass
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-options: Prune=confirm,Delete=confirm
  - target:
      group: postgresql.cnpg.io
      kind: Cluster
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-options: Prune=confirm,Delete=confirm
  - target:
      group: apps
      kind: StatefulSet
      name: ai-vector-db
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-options: Prune=confirm,Delete=confirm
