apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - storage.yaml
patches:
  - path: deployment-patch.yaml
configMapGenerator:
  - name: ai-model-preparation
    namespace: ai
    files:
      - prepare-models.sh
