apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-config
  namespace: app
spec:
  provider: aws
  parameters:
    region: ap-northeast-2
    usePodIdentity: 'false'
    objects: |
      - objectName: "/prod/backend/db-url"
        objectType: ssmparameter
        objectAlias: DB_URL
        filePermission: '0444'
      - objectName: "/prod/backend/db-username"
        objectType: ssmparameter
        objectAlias: DB_USERNAME
        filePermission: '0444'
      - objectName: "/prod/backend/db-password"
        objectType: ssmparameter
        objectAlias: DB_PASSWORD
        filePermission: '0444'
      - objectName: "/prod/backend/redis-password"
        objectType: ssmparameter
        objectAlias: spring.data.redis.password
        filePermission: '0444'
      - objectName: "/prod/backend/jwt-secret"
        objectType: ssmparameter
        objectAlias: JWT_SECRET
        filePermission: '0444'
      - objectName: "/prod/backend/kakao-client-id"
        objectType: ssmparameter
        objectAlias: KAKAO_CLIENT_ID
        filePermission: '0444'
      - objectName: "/prod/backend/kakao-client-secret"
        objectType: ssmparameter
        objectAlias: KAKAO_CLIENT_SECRET
        filePermission: '0444'
      - objectName: "/prod/backend/naver-client-id"
        objectType: ssmparameter
        objectAlias: NAVER_CLIENT_ID
        filePermission: '0444'
      - objectName: "/prod/backend/naver-client-secret"
        objectType: ssmparameter
        objectAlias: NAVER_CLIENT_SECRET
        filePermission: '0444'
      - objectName: "/prod/backend/mail-host"
        objectType: ssmparameter
        objectAlias: MAIL_HOST
        filePermission: '0444'
      - objectName: "/prod/backend/mail-username"
        objectType: ssmparameter
        objectAlias: MAIL_USERNAME
        filePermission: '0444'
      - objectName: "/prod/backend/mail-password"
        objectType: ssmparameter
        objectAlias: MAIL_PASSWORD
        filePermission: '0444'
      - objectName: "/prod/backend/mail-from"
        objectType: ssmparameter
        objectAlias: MAIL_FROM
        filePermission: '0444'
      - objectName: "/prod/backend/oauth-frontend-redirect-url"
        objectType: ssmparameter
        objectAlias: OAUTH_FRONTEND_REDIRECT_URL
        filePermission: '0444'
      - objectName: "/prod/backend/ai-base-url"
        objectType: ssmparameter
        objectAlias: AI_BASE_URL
        filePermission: '0444'
      - objectName: "/prod/backend/backend-auth-token"
        objectType: ssmparameter
        objectAlias: BACKEND_AUTH_TOKEN
        filePermission: '0444'
