apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storageclass.yaml
  - service.yaml
  - statefulset.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: ai-vector-db-init
    namespace: ai
    files:
      - 00-load-password.sh
      - init.sql
