apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ollama-vector-db
  namespace: ai
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ai-vector-db
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ai
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ai-ollama
      ports:
        - protocol: TCP
          port: 5432
  egress: []
