---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: prod-observability-metrics
  patch: '[{"op":"add","path":"/spec/sources/0/helm/valueFiles/2","value":"$values/platform/observability/alerts/discord/values.yaml"},{"op":"add","path":"/spec/sources/0/helm/valueFiles/3","value":"$values/platform/observability/alerts/discord/prod/values.yaml"},{"op":"add","path":"/spec/sources/1/helm/valuesObject/discord","value":{"enabled":true}}]'
