apiVersion: v1
kind: Service
metadata:
  name: ai-ollama
  namespace: ai
  labels:
    app.kubernetes.io/name: ai-ollama
    app.kubernetes.io/part-of: jangingmall
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ai-ollama
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
