apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: redis-config
  namespace: app
spec:
  provider: aws
  parameters:
    region: ap-northeast-2
    usePodIdentity: 'false'
    objects: |
      - objectName: "/staging/backend/redis-password"
        objectType: ssmparameter
        objectAlias: password
        filePermission: '0444'
