apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../collectors
configMapGenerator:
  - name: trace-environment
    namespace: monitoring
    literals:
      - OBS_ENV=prod
