apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: stage-backup
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/Jangingmall/infra.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: database
    - server: https://kubernetes.default.svc
      namespace: cnpg-system
  namespaceResourceWhitelist:
    - group: barmancloud.cnpg.io
      kind: ObjectStore
    - group: postgresql.cnpg.io
      kind: ScheduledBackup
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
