apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-aws-load-balancer-controller
  namespace: argocd
spec:
  project: stage-platform
  sources:
  - repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.14.0
    helm:
      releaseName: aws-load-balancer-controller
      valueFiles:
      - "$values/platform/aws-load-balancer-controller/values.yaml"
      - "$values/platform/aws-load-balancer-controller/runtime/stage.yaml"
  - repoURL: https://github.com/Jangingmall/infra.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: aws-load-balancer-webhook
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: aws-load-balancer-webhook
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
  syncPolicy:
    automated:
      enabled: false
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - FailOnSharedResource=true
    - RespectIgnoreDifferences=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-metrics-server
  namespace: argocd
spec:
  project: stage-platform
  sources:
  - repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: 3.14.0
    helm:
      releaseName: metrics-server
      valueFiles:
      - "$values/platform/metrics-server/values.yaml"
  - repoURL: https://github.com/Jangingmall/infra.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  ignoreDifferences:
  - group: apiregistration.k8s.io
    kind: APIService
    name: v1beta1.metrics.k8s.io
    jsonPointers:
    - /spec/caBundle
  syncPolicy:
    automated:
      enabled: false
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - FailOnSharedResource=true
    - RespectIgnoreDifferences=true
