apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Enable only with environment-specific Kubernetes API, STS, and S3 rules.
resources:
  - default-deny-egress.yaml
  - allow-cnpg-internal-egress.yaml
