---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-cloudnative-pg
  namespace: argocd
spec:
  project: prod-platform
  sources:
  - repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.29.0
    helm:
      releaseName: cloudnative-pg
      valueFiles:
      - "$values/platform/cloudnative-pg/values.yaml"
  - repoURL: https://github.com/Jangingmall/infra.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - FailOnSharedResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-argo-rollouts
  namespace: argocd
spec:
  project: prod-platform
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.43.1
    helm:
      releaseName: argo-rollouts
      valueFiles:
      - "$values/platform/argo-rollouts/values.yaml"
  - repoURL: https://github.com/Jangingmall/infra.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - FailOnSharedResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-secrets-store-csi
  namespace: argocd
spec:
  project: prod-platform
  sources:
  - repoURL: https://aws.github.io/secrets-store-csi-driver-provider-aws
    chart: secrets-store-csi-driver-provider-aws
    targetRevision: 3.1.3
    helm:
      releaseName: secrets-store-csi
      valueFiles:
      - "$values/platform/secrets-store-csi/values.yaml"
  - repoURL: https://github.com/Jangingmall/infra.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - FailOnSharedResource=true
